app/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login_manager

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(60), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    
    @property
    def password(self):
        """
        Prevent password from being accessed
        """
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        """
        Set password to a hashed password
        """
        self.password_hash = generate_password_hash(password)
        
    def verify_password(self, password):
        """
        Check if hashed password matches actual password
        """
        return check_password_hash(self.password_hash, password)
        
    def __repr__(self):
        return '<Employee: {}>'.format(self.username)

        
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
        
        
class Teacher(db.Model):
    __tablename__ = 'teachers'

    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(20), index=True)
    last_name = db.Column(db.String(20), index=True)
    email = db.Column(db.String(60), index=True, unique=True)
    phone = db.Column(db.String(20))
    class_id = db.Column(db.Integer, db.ForeignKey('classes.id'))
    #middle_name = db.Column(db.String(20), index=True)
    #classroom = db.relationship("Classroom", uselist=False, back_populates="teacher")

    def __repr__(self):
        return '<Teacher: {} {}>'.format(self.first_name, self.last_name)


class Classroom(db.Model):
    __tablename__ = 'classes'

    id = db.Column(db.Integer, primary_key=True)
    level = db.Column(db.Integer, index=True)
    room = db.Column(db.String(10))
    #teacher_id = db.column(db.Integer, db.ForeignKey('teachers.id'))
    teacher = db.relationship("Teacher", backref="classroom", lazy='dynamic')

    def __repr__(self):
        return '<Classroom: Level {}, Teacher {}>'.format(self.level, self.teacher_id)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError
from wtforms.validators import DataRequired, Email

from models import Teacher

class TeacherForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])

app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField, ValidationError
from wtforms.validators import DataRequired, Email

from ..models import User

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

app/__init__.py
# third-party imports
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_wtf.csrf import CSRFProtect

# local imports
from config import app_config

# app-wide variables
db = SQLAlchemy()
login_manager = LoginManager()
csrf = CSRFProtect()

def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('config.py')
    app.logger.setLevel(app_config[config_name].LOGLEVEL)
    
    Bootstrap(app)    
    db.init_app(app)  
    csrf.init_app(app)      
    login_manager.init_app(app)
    login_manager.login_message = "Please login before accessing other pages."
    login_manager.login_view = "auth.login"     
    migrate = Migrate(app, db)
    
    from app import models
    
    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)
    
    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)

    return app

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__)

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import flash, redirect, render_template, url_for
from flask_login import login_required

from . import home

@home.route('/')
@home.route('/index')
def index():
    return redirect(url_for('auth.login'))
    
    
@home.route('/dashboard')
@login_required
def dashboard():
    return render_template('home/dashboard.html')

app/templates/add_teacher.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block content %}
<div class="container">
      <h2 class="sub-header">Add a new teacher</h2>
      <form action="" method="post">
            {{form.hidden_tag()}}
            <div class="table-responsive">
                <table>
                    {{ render_field(form.first_name, size=20) }}
                    {{ render_field(form.last_name, size=20) }}
                    {{ render_field(form.email, size=60) }}
                    <tr>
                        <td></td>
                        <td><button type="submit">Submit</button></td>
                    </tr>
                </table>
            </div>
      </form>
</div>
{% endblock %}

app/templates/base.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>SAT -- SPELL Attendance Tracker</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">


        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/styles.css') }}?v=poop" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>        
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('home.index') }}">SPELL Attendance</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %} 
                <li><a><i class="fa fa-user"></i>  Hi, {{ current_user.email }}!</a></li>
                <li><a class="btn btn-success" href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Login <span class="glyphicon glyphicon-log-in"></span></a></li>
                <li><a href="{{ url_for('auth.register') }}">Register <span class="glyphicon glyphicon-user"></span></a></li>
                {% endif %}
            </ul><!--/.navbar-collapse -->
        </div>
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="container">
        {% block content %}
        {% endblock %}
        <div class="push"></div>
    </div>

    </body>
</html>

app/templates/form_macros.html
{% macro render_field(field) %}
    <tr {% if field.errors %} class="error" {% endif %}>
        <td>{{ field.label }}</td>
        <td>{{ field(**kwargs)|safe }}</td>
    </tr>
    <tr class="error">
        <td></td>
        <td>
            <ul>
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </td>
    </tr>
{% endmacro %}

app/templates/home/dashboard.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
  <div class="center">
    <h1>Dashboard</h1>
  </div>
</div>
{% endblock %}

app/templates/home/index.html
{% extends "base.html" %}

{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>SAT -- SPELL Attendance Tracker</h1>
        <p>Hello SPELL teacher. Use this application to input your weekly attendance for your SPELL classes.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>
{% endblock %}

app/templates/list.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
          <h2 class="sub-header">Teachers</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Email</th>
                </tr>
              </thead>
              <tbody>
              {% for teacher in teachers %}
                <tr>
                  <td>1,001</td>
                  <td>{{ teacher }}</td>
                  <td>{{ teacher.email }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
    </div>
{% endblock %}